name: Check repository files

on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '45 */6 * * *'

  push:
    branches:
      - master  
  
  pull_request: {}

concurrency:
    group: stable-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  check:
    name: check repository files
    if: |
      github.repository == 'ioBroker/ioBroker.repositories'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: npm i
      - run: npm run test
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
