name: New PR comment

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: |
      github.repository == 'ioBroker/ioBroker.repositories' &&
      github.event.issue.pull_request &&
      github.event.comment.user.login != 'mcm1957'

    runs-on: ubuntu-latest

    steps:
      - run: echo user ${{github.event.comment.user.login}}
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["*📬"]
            })
